// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkQghjRPJ-LF-Iiu7dZSerZHdFStRIRCk',
    appId: '1:261685193715:web:818c79fd186bab7ec48086',
    messagingSenderId: '261685193715',
    projectId: 'ftf3-4c575',
    authDomain: 'ftf3-4c575.firebaseapp.com',
    storageBucket: 'ftf3-4c575.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAl1WwVDr295vxA50FKJjMWgDmPb7kFmGY',
    appId: '1:261685193715:android:6354ea91daa62aafc48086',
    messagingSenderId: '261685193715',
    projectId: 'ftf3-4c575',
    storageBucket: 'ftf3-4c575.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtbZx9iq3K28DgpT4GnooAdeeIPa-wwgk',
    appId: '1:261685193715:ios:83f539d7cfdb9bd2c48086',
    messagingSenderId: '261685193715',
    projectId: 'ftf3-4c575',
    storageBucket: 'ftf3-4c575.firebasestorage.app',
    iosBundleId: 'com.example.ftf3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtbZx9iq3K28DgpT4GnooAdeeIPa-wwgk',
    appId: '1:261685193715:ios:83f539d7cfdb9bd2c48086',
    messagingSenderId: '261685193715',
    projectId: 'ftf3-4c575',
    storageBucket: 'ftf3-4c575.firebasestorage.app',
    iosBundleId: 'com.example.ftf3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkQghjRPJ-LF-Iiu7dZSerZHdFStRIRCk',
    appId: '1:261685193715:web:4fe43464f4f73b39c48086',
    messagingSenderId: '261685193715',
    projectId: 'ftf3-4c575',
    authDomain: 'ftf3-4c575.firebaseapp.com',
    storageBucket: 'ftf3-4c575.firebasestorage.app',
  );
}
